integrated_risk_detection:
  description: >
    제공된 건설 현장 이미지({image_path})와 작업 설명({tasks})을 동시에 분석하여, 
    현장 조건과 작업의 조합으로 인해 발생할 수 있는 모든 잠재적 위험을 식별하고 나열합니다. 
    식별된 각 위험 요소는 현장과 작업 간의 상호작용이 위험을 어떻게 초래하는지 명확히 설명해야 합니다.
    **모든 응답은 반드시 한국어로 작성해야 합니다.**
  expected_output: >
    출력은 식별된 각 위험 요소에 대해 다음 섹션을 포함하는 구조화된 형식을 따라야 합니다:
    1. **위험 요소**: 현장과 작업의 조합을 기반으로 식별된 위험 요소를 명확히 설명합니다.
    2. **위험 시나리오**: 이 위험이 사고나 사건으로 이어질 수 있는 잠재적 시나리오를 자세히 설명합니다.
    3. **결과**: 이 위험이 현실화될 경우의 가능한 결과(예: 부상, 재산 손실)를 설명합니다.
    모든 식별된 위험이 포함되도록 하고, 형식은 다음 에이전트가 쉽게 이해할 수 있도록 일관성을 유지해야 합니다.

risk_assessment:
  description: >
    제공된 목록을 기반으로 식별된 위험 요소의 위험 정도를 평가합니다. 각 위험 요소를 두 가지 기준(**심각도** 및 **빈도**)에 따라 평가합니다.

    **심각도(S)**는 다음 세부 기준에 따라 1에서 4까지의 점수로 평가됩니다:
    1. 부상이 없거나 응급처치만 필요한 부상 / 건설 기간에 영향을 미치지 않는 사소한 물체(또는 인접 구조물) 손상.
    2. 비치명적인 부상을 포함한 사소한 사건 / 3일 이내의 건설 기간 손실을 초래하는 사소한 물체(또는 인접 구조물) 손상.
    3. 장애를 초래하는 부상 / 1주 이상의 건설 기간 손실을 초래하는 심각한 물체(또는 인접 구조물) 손상.
    4. 사망 또는 장기 장애를 초래하는 부상 / 건설 중 물체(또는 인접 구조물)의 붕괴.

    **빈도(F)**는 다음 세부 기준에 따라 1에서 4까지의 점수로 평가됩니다:
    1. 매우 드물다: 지난 5년간 동일하거나 유사한 사고의 기록이 없거나 전문가가 가능성을 매우 낮게 평가.
    2. 드물다: 지난 3년간 동일하거나 유사한 사고의 기록이 있거나 전문가가 가능성을 낮게 평가.
    3. 가능성이 높다: 지난 1년간 동일하거나 유사한 사고의 기록이 있거나 전문가가 가능성을 높게 평가.
    4. 매우 가능성이 높다: 지난 3개월간 동일하거나 유사한 사고의 기록이 있거나 전문가가 가능성을 매우 높게 평가.

    전체 위험 등급은 심각도(S)와 빈도(F)를 곱하여 결정됩니다. 
    계산된 위험 등급이 8 이상이면 위험이 용납되지 않으며 위험 감소 조치를 마련해야 합니다. 
    위험 등급이 3 이하인 경우, 위험이 용납 가능한 것으로 간주되어 추가 조치가 필요하지 않습니다. 
    다른 모든 경우에는 위험이 용납되지 않으며 위험 감소 조치를 준비해야 합니다.
    각 위험 요소에 대해 심각도 및 빈도 평가에 대한 이유를 설명하여, 할당된 점수에 대한 정당성을 제공합니다.
    **모든 응답은 반드시 한국어로 작성해야 합니다.**
  expected_output: >
    출력에는 다음과 같은 열이 포함된 표가 있어야 합니다:
    1. **위험 요소**: 제공된 목록에서 식별된 위험 요소.
    2. **심각도(S)**: 위의 세부 기준에 따라 평가된 심각도 점수(1-4).
    3. **빈도(F)**: 위의 세부 기준에 따라 평가된 빈도 점수(1-4).
    4. **위험 등급**: 심각도와 빈도의 곱으로 계산된 값(S * F).
    5. **위험 수준**: 위험 등급에 따라 위험이 용납 가능한지 여부를 나타냄(예: 용납 가능, 용납 불가).

    표 아래에는 각 위험 요소에 대한 위험 평가에 대한 이유를 설명하며, 할당된 심각도 및 빈도 평가 점수의 정당성을 제공합니다. 
    형식의 일관성을 유지하며, 평가 결과와 이유 이외의 추가 정보를 포함하지 않습니다.

risk_reduction:
  description: >
    제공된 위험 평가 결과를 분석합니다. 각 위험 요소에 대해 위험 등급이 8 이상이면, 
    구체적인 위험 감소 조치를 제안해야 합니다. 이러한 조치는 위험 등급을 3 이하로 낮추는 것을 목표로 해야 하며, 
    위험의 원인을 직접적으로 해결하는 실용적인 대안을 제시해야 합니다.
    **모든 응답은 반드시 한국어로 작성해야 합니다.**
  expected_output: >
    출력은 매 실행 시 다음 템플릿을 따르는 구조화되고 일관된 형식이어야 합니다:

    1. **위험 요소**: 식별된 위험 요소를 설명합니다.
    2. **위험 등급**: 위험 평가 결과를 기반으로 한 현재의 위험 등급.
    3. **위험 감소 조치**: 위험 등급을 3 이하로 낮출 수 있는 구체적이고 실행 가능한 조치를 나열합니다.

    위험 등급이 3 이하인 경우, 단순히 '추가 조치 불필요'라고 명시합니다.

    모든 출력의 형식이 일관되도록 하고, 지정된 템플릿에서 벗어나지 않도록 합니다.